version: '3'
services:
  solr-map:
    image: solr:8
    ports:
     - "8983:8983"
    volumes:
    - /home/simone/project/social-map/code/docker-sm/dev/solr-data:/var/solr/data
    - /home/simone/project/social-map/code/docker-sm/dev/solr-server:/opt/solr/server
    command:
      - solr-precreate
      - social-map
